name: CI

on:
  push:
  pull_request:

jobs:
  linux_i686_and_macos:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build:
        - macos
        - linux-i686-gcc
        include:
        - build: macos
          os: macos-10.15
        - build: linux-i686-gcc
          os: ubuntu-20.04
          arch: i686

    env:
      CI_TARGET_ARCH: ${{ matrix.arch }}
      CI_EVENT: ${{ github.event_name }}
      CC: ${{ matrix.cc }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install dependencies
      run: ./ci/actions-install.sh
    - name: Build
      run: ./ci/actions-build.sh
    - name: Smoke test
      run: ./ci/actions-smoke-test.sh
    - name: Full test
      run: ./ci/actions-full-test.sh
